version: '3.8'

services:
  pisignage-web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./media:/var/www/html/media
      - ./logs:/var/log/pisignage
    environment:
      - PHP_ENV=development
      - PISIGNAGE_DEBUG=true
    depends_on:
      - pisignage-db
    networks:
      - pisignage-network

  pisignage-db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: pisignage_root
      MYSQL_DATABASE: pisignage
      MYSQL_USER: pisignage
      MYSQL_PASSWORD: pisignage_pass
    volumes:
      - pisignage_db_data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - pisignage-network

  pisignage-player:
    build:
      context: .
      dockerfile: docker/Dockerfile.player
    environment:
      - DISPLAY=:99
      - PISIGNAGE_API_URL=http://pisignage-web
    volumes:
      - ./media:/app/media
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      - pisignage-web
    networks:
      - pisignage-network
    # For X11 forwarding in development
    privileged: true

  pisignage-monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pisignage-network

volumes:
  pisignage_db_data:

networks:
  pisignage-network:
    driver: bridge