#!/usr/bin/expect -f
set timeout 120
spawn ssh -o StrictHostKeyChecking=no pi@192.168.1.106
expect "password:"
send "palmer00\r"
expect "$ "
send "cd /home/pi && rm -rf Pi-Signage && git clone https://github.com/elkir0/Pi-Signage.git\r"
expect "$ "
send "cd Pi-Signage/raspberry-pi-installer/scripts && chmod +x *.sh\r"
expect "$ "
send "echo 'Repository cloned and ready'\r"
expect "$ "
send "exit\r"
expect eof